version: "1.0"

services:
  #             _   _
  #   __ _  ___| |_| |__
  #  / _` |/ _ \ __| '_ \
  # | (_| |  __/ |_| | | |
  #  \__, |\___|\__|_| |_|
  #  |___/
  geth:
    image: ethereum/client-go:${GETH_VERSION:-v1.14.5}
    ports:
      - ${EC_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${EC_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${EC_PORT_HTTP:-8545}:8545 # JSON-RPC
      - ${EC_PORT_ENGINE:-8551}:8551 # ENGINE-API
      - ${EC_PORT_METRIC:-6060}:6060 # METRICS
    command: |
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts="*"
      --http.api="db,eth,net,engine,rpc,web3"
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins="*"
      --ws.api="eth,net,web3"
      --authrpc.jwtsecret="/root/jwt/jwt.hex"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
      --bootnodes=${EC_BOOTNODES:-enode://e31aa249638083d34817eed2b499ccd4b0718a332f0ea530e3062e13f624cb03a7d6b6e0460193ee87b5fc12e73a726070a3126ef53492ffbdc5e6c102f6dfb3@34.64.198.56:30303,enode://3f2f85e2e711f198fb7324b74fab6a0599b2534774f3aa26241dbbabe870b650574324da01aa98ee24ce97c8d76362a2db03034a6ddff43119ccfdc269663cbf@34.47.79.13:30303,enode://7a2f67d22b12e10c6ba9cd951866dda6471604be5fbd5102217dbad1cc56e590befd2009ecc99958a468a5b8e0dc28e14d9b6822491719c93199be6aa0319077@34.124.220.31:30303}
      --networkid=${EC_NETWORK_ID:-80084}
      --snapshot=false
      --syncmode=snap
      --nat=${EC_NAT:-}
      --config=/root/config.toml
    volumes:
      - ./data/geth:/root/.ethereum
      - ./geth/config.toml:/root/config.toml
      - ${EC_JWT_PATH:-~/.beacond/config/jwt.hex}:/root/jwt/jwt.hex
    restart: unless-stopped